name: hack2k19sbg
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.0.3
  http: ^0.12.0+2
  flutter_spinkit: ^2.1.0
  webview_flutter: ^0.3.10+3
  url_launcher: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true

  assets:
    - assets/food1.jpeg
    - assets/food2.jpeg
    - assets/food3.jpeg
    - assets/food4.jpeg
    - assets/food5.jpeg
    - assets/food6.jpeg
    - assets/food7.jpeg
    - assets/food8.jpeg
    - assets/food9.jpeg
    - assets/food10.jpeg
    - assets/food11.jpeg
    - assets/food12.jpg
    - assets/zest.png
    - assets/sbg_logo.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
